// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/device/transport/grpc/pb/svcdevice.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	services/device/transport/grpc/pb/svcdevice.proto

It has these top-level messages:
	UnlockRequest
	UnlockResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UnlockRequest struct {
	EventId  []byte `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DeviceId []byte `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
}

func (m *UnlockRequest) Reset()                    { *m = UnlockRequest{} }
func (m *UnlockRequest) String() string            { return proto.CompactTextString(m) }
func (*UnlockRequest) ProtoMessage()               {}
func (*UnlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UnlockRequest) GetEventId() []byte {
	if m != nil {
		return m.EventId
	}
	return nil
}

func (m *UnlockRequest) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *UnlockRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type UnlockResponse struct {
	EventCaption  string `protobuf:"bytes,1,opt,name=event_caption,json=eventCaption" json:"event_caption,omitempty"`
	DeviceCaption string `protobuf:"bytes,2,opt,name=device_caption,json=deviceCaption" json:"device_caption,omitempty"`
}

func (m *UnlockResponse) Reset()                    { *m = UnlockResponse{} }
func (m *UnlockResponse) String() string            { return proto.CompactTextString(m) }
func (*UnlockResponse) ProtoMessage()               {}
func (*UnlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UnlockResponse) GetEventCaption() string {
	if m != nil {
		return m.EventCaption
	}
	return ""
}

func (m *UnlockResponse) GetDeviceCaption() string {
	if m != nil {
		return m.DeviceCaption
	}
	return ""
}

func init() {
	proto.RegisterType((*UnlockRequest)(nil), "pb.UnlockRequest")
	proto.RegisterType((*UnlockResponse)(nil), "pb.UnlockResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Device service

type DeviceClient interface {
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error)
}

type deviceClient struct {
	cc *grpc.ClientConn
}

func NewDeviceClient(cc *grpc.ClientConn) DeviceClient {
	return &deviceClient{cc}
}

func (c *deviceClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	out := new(UnlockResponse)
	err := grpc.Invoke(ctx, "/pb.Device/Unlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Device service

type DeviceServer interface {
	Unlock(context.Context, *UnlockRequest) (*UnlockResponse, error)
}

func RegisterDeviceServer(s *grpc.Server, srv DeviceServer) {
	s.RegisterService(&_Device_serviceDesc, srv)
}

func _Device_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Device/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Device_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Device",
	HandlerType: (*DeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unlock",
			Handler:    _Device_Unlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/device/transport/grpc/pb/svcdevice.proto",
}

func init() { proto.RegisterFile("services/device/transport/grpc/pb/svcdevice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0x55, 0xd6, 0xee, 0xd0, 0x2d, 0x38, 0xa7, 0xaa, 0x97, 0xb2, 0x22, 0xf4, 0xb4,
	0xa1, 0x7a, 0xf4, 0xa8, 0x97, 0x5e, 0x17, 0x3c, 0x29, 0x48, 0x37, 0x19, 0x64, 0x51, 0x92, 0x31,
	0x89, 0xfb, 0xfb, 0xa5, 0x33, 0x2d, 0xd8, 0x53, 0x92, 0xef, 0xbd, 0xbc, 0x97, 0x0c, 0x6c, 0x12,
	0xc5, 0x69, 0xb4, 0x94, 0x8c, 0xa3, 0xfd, 0x6a, 0x72, 0xdc, 0xf9, 0xc4, 0x21, 0x66, 0xf3, 0x19,
	0xd9, 0x1a, 0x1e, 0x4c, 0x9a, 0xac, 0x6a, 0x1d, 0xc7, 0x90, 0x03, 0x96, 0x3c, 0xb4, 0x6f, 0xd0,
	0xbc, 0xfa, 0xef, 0x60, 0xbf, 0x7a, 0xfa, 0xf9, 0xa5, 0x94, 0xf1, 0x1a, 0x66, 0x34, 0x91, 0xcf,
	0x1f, 0xa3, 0x5b, 0x16, 0xab, 0x62, 0x3d, 0xef, 0x2f, 0xe5, 0xbc, 0x75, 0x78, 0x0b, 0xb5, 0xde,
	0xdf, 0x6b, 0xa5, 0x68, 0x33, 0x05, 0x5b, 0x87, 0x08, 0x17, 0x36, 0x38, 0x5a, 0x9e, 0xaf, 0x8a,
	0x75, 0xdd, 0xcb, 0xbe, 0x7d, 0x87, 0xc5, 0x31, 0x3c, 0x71, 0xf0, 0x89, 0xf0, 0x0e, 0x1a, 0x4d,
	0xb7, 0x3b, 0xce, 0x63, 0xf0, 0x52, 0x51, 0xf7, 0x73, 0x81, 0xcf, 0xca, 0xf0, 0x1e, 0x16, 0x87,
	0x9e, 0xa3, 0xab, 0x14, 0x57, 0xa3, 0xf4, 0x60, 0x7b, 0x78, 0x82, 0xea, 0x45, 0x00, 0x6e, 0xa0,
	0xd2, 0x1e, 0xbc, 0xea, 0x78, 0xe8, 0x4e, 0x3e, 0x74, 0x83, 0xff, 0x91, 0x3e, 0xa3, 0x3d, 0x1b,
	0x2a, 0x19, 0xc1, 0xe3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0xe5, 0x4e, 0x8f, 0x37, 0x01,
	0x00, 0x00,
}
